'use strict';

/**
 * @ngdoc function
 * @name srcApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the srcApp
 */
angular.module('srcApp')
  .controller('MainCtrl', ['$scope', 'sections', function ($scope, sections) {
    $scope.sections = sections();
  }])

  .factory('sections', function() {
    return function() {
      return [
      { 'Title': 'Out of Character',
        'Glyph': 'glyphicon-ok',
        'Url': '/outofcharacter',
        'Articles': [
          { 'Title': 'A Brief Guide to History',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/A+Brief+Guide+to+History.pdf'},
          { 'Title': 'Companies & Corporations',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Companies+%26+Corporations.pdf'},
          { 'Title': 'Groups & Organisations',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Groups+%26+Organisations.pdf'},
          { 'Title': 'The Writer\'s Guide',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Writer%27s+Guide.pdf'},
            ]
        },

      { 'Title': 'Mexal\'s Letters Home',
        'Glyph': 'glyphicon-envelope',
        'Url': '/mexalsletters',
        'Articles': [
          { 'Title': '2493-03 - Kruger',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2493-03++-+Kruger.pdf'},
          { 'Title': '2494-06 - Laverii-426',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2493-06++-+Laverii-426.pdf'},
          { 'Title': '2494-09 - X244',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2493-09+-+X244.pdf'},
          { 'Title': '2494-12 - Juliette',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2493-12+-+Juliette.pdf'},
          { 'Title': '2495-01 - Grant\'s World',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2495-01+-+Grant%27s+World.pdf'},
          { 'Title': '2495-02 - Heurls',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2495-02+-+Heurls.pdf'},
          { 'Title': '2495-03 - Connet',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2495-03+-+Connet.pdf'},
          { 'Title': '2495-04 - Groombridge',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2495-04+-+Groombridge.pdf'},
          { 'Title': '2495-05 - Marie Celesta',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2495-05+-+Marie+Celesta.pdf'},
          { 'Title': '2495-07 - Hal',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mexal%27s+Letters/2495-07+-+Hal.pdf'},
            ]},

      { 'Title': 'Mission Reports',
        'Glyph': 'glyphicon-screenshot',
        'Url': '/missionreports',
        'Articles': [
            { 'Title': '2494-03 - Mission "Sidewinder" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2494-03+Mission+%22Sidewinder%22+(Calvin).pdf'},
            { 'Title': '2494-04 - Mission "Ogre" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2494-04+Mission+%22Ogre%22+(Calvin).pdf'},
            { 'Title': '2494-06 - Mission "Pegasus" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2494-06+Mission+%22Pegasus%22+(Calvin).pdf'},
            { 'Title': '2495-01 - Mission "-C-L-A-S-S-I-F-I-E-D-" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2494-12+Mission+%22-C-L-A-S-S-I-F-I-E-D%22+(Calvin).pdf'},
            { 'Title': '2494-03 - Mission "Nightside" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2495-01+Mission+%22Nightside%22+(Calvin).pdf'},
            { 'Title': '2495-05 - Boarding Report "SS Marie Celesta" (Oslo).',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2495-05+Boarding+Report+%22SS+Marie+Celesta%22+(Oslo).pdf'},
            { 'Title': '2494-03 - Mission "Omaha" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2495-07+Mission+%22Omaha%22+(Calvin).pdf'},
            { 'Title': '2494-03 - Mission "Nova" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2495-11+Mission+%22Nova%22+(Calvin).pdf'},
            { 'Title': '2494-03 - Mission "Intruder" (Calvin)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2496-02+Mission+%22Intruder%22+(Calvin).pdf'},
            { 'Title': '2494-03 - Mission "Intruder" - SIB Report (Rumpole)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2496-02+Mission+%22Intruder%22+-+SIB+Report+(Rumpole).pdf'},
            { 'Title': '2494-03 - Mission "Red Storm" (Turner)',
              'Content': '',
              'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Mission+Reports/2496-03+Mission+%22Red+Storm%22+(Turner).pdf'},
        ]},

      { 'Title': 'Marine\'s Handbook',
        'Glyph': 'glyphicon-book',
        'Url': '/marineshandbook',
        'Articles': [
          { 'Title': 'Contents',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Contents.pdf'},
          { 'Title': 'Basic Combat Training',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Basic+Combat+Training.pdf'},
          { 'Title': 'Patrolling',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Patrolling.pdf'},
          { 'Title': 'Scouting',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Scouting.pdf'},
          { 'Title': 'Sniper',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Sniper.pdf'},
          { 'Title': 'Med-Tech 4',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+MedTech+4.pdf'},
          { 'Title': 'Med-Tech 3',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+MedTech+3.pdf'},
          { 'Title': 'Med-Tech 2',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+MedTech+2.pdf'},
          { 'Title': 'Med-Tech 1',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+MedTech+1.pdf'},
          { 'Title': 'EOD Specialist 4',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+EOD+Specialist+4.pdf'},
          { 'Title': 'Armourer 4',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Armourer+4.pdf'},
          { 'Title': 'Radio Operator 2',
            'Content': '',
            'PdfUrl': 'https://s3-eu-west-1.amazonaws.com/5coy-cmc/Marine%27s+Handbook/Marine%27s+Handbook+-+Radio+Operator+2.pdf'},

                    ]},
    ]; };
  });
