#!/usr/bin/env bash
#
# migrate-media-paths.sh
#
# One-shot migration of the 5coy-archive media S3 bucket from its pre-cleanup
# layout to the canonical post-cleanup layout defined in
# docs/specs/51-corpus-cleanup.md.
#
# Reads scripts/rename-map.json (generated by scripts/generate-rename-map.py).
# Default is --dry-run; pass --execute to perform live moves.
#
# Idempotent: if a target object already exists at the canonical path and the
# source no longer exists, the move is skipped. Safe to re-run.
#
# Requires: aws cli on PATH, jq, AWS creds with s3 mv permissions on the bucket.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_MAP="${REPO_ROOT}/scripts/rename-map.json"

usage() {
  cat >&2 <<EOF
USAGE:
  $(basename "$0") <bucket> [--execute] [--reverse] [--map <path>] [--concurrency <n>]

ARGUMENTS:
  <bucket>            S3 bucket name (e.g. 5coy-media-prod).

OPTIONS:
  --execute           Perform live moves. Default: --dry-run.
  --reverse           Move canonical → legacy (rollback). Default: legacy → canonical.
  --map <path>        Path to rename-map.json. Default: scripts/rename-map.json.
  --concurrency <n>   Parallel aws s3 mv invocations. Default: 8.
  -h | --help         Show this message.

EXIT CODES:
  0   success (dry-run or execute)
  1   precondition failure
  2   one or more moves failed during --execute

This script ONLY touches /media/* PDF objects. Content files in
web/wwwroot/content/ are not S3 objects and are handled by git mv.
EOF
}

# --- args ---
BUCKET=""
EXECUTE=0
REVERSE=0
MAP="${DEFAULT_MAP}"
CONCURRENCY=8

while [[ $# -gt 0 ]]; do
  case "$1" in
    --execute) EXECUTE=1; shift ;;
    --reverse) REVERSE=1; shift ;;
    --map) MAP="$2"; shift 2 ;;
    --concurrency) CONCURRENCY="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *)
      if [[ -z "$BUCKET" ]]; then
        BUCKET="$1"
      else
        echo "Unexpected positional arg: $1" >&2
        usage; exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$BUCKET" ]]; then
  usage; exit 1
fi

# --- preflight ---
command -v aws >/dev/null 2>&1 || { echo "aws cli not on PATH" >&2; exit 1; }
command -v jq  >/dev/null 2>&1 || { echo "jq not on PATH" >&2; exit 1; }
[[ -f "$MAP" ]] || { echo "Rename map not found: $MAP" >&2; exit 1; }

MODE="DRY-RUN"
[[ $EXECUTE -eq 1 ]] && MODE="EXECUTE"
DIRECTION="legacy → canonical"
[[ $REVERSE -eq 1 ]] && DIRECTION="canonical → legacy (REVERSE)"

echo "=== migrate-media-paths.sh ==="
echo "  Bucket:      s3://${BUCKET}"
echo "  Map:         ${MAP}"
echo "  Mode:        ${MODE}"
echo "  Direction:   ${DIRECTION}"
echo "  Concurrency: ${CONCURRENCY}"
echo

# --- build move plan ---
# Filter map to PDF kind only (content moves are local git mv, not S3).
PLAN_JSON="$(jq '.moves | map(select(.kind == "pdf" or .kind == "extra"))' "$MAP")"
TOTAL="$(echo "$PLAN_JSON" | jq 'length')"
echo "Total PDF moves declared in map: $TOTAL"

# Inventory current bucket. One key per line, no s3:// prefix.
echo "Listing bucket contents..."
INVENTORY="$(mktemp)"
trap 'rm -f "$INVENTORY"' EXIT
aws s3 ls "s3://${BUCKET}/" --recursive | awk '{print $4}' | sort > "$INVENTORY"
INVENTORY_COUNT="$(wc -l < "$INVENTORY")"
echo "  ${INVENTORY_COUNT} objects in bucket"
echo

# --- classify each declared move ---
declare -a TO_MOVE=()
SKIP_ALREADY_DONE=0
SKIP_MISSING_BOTH=0

# jq output: src<TAB>dst per line, accounting for --reverse.
JQ_FILTER='.[] | [.legacy, .canonical] | @tsv'
[[ $REVERSE -eq 1 ]] && JQ_FILTER='.[] | [.canonical, .legacy] | @tsv'

while IFS=$'\t' read -r SRC_PATH DST_PATH; do
  # Strip leading slash; S3 keys don't have it.
  SRC_KEY="${SRC_PATH#/}"
  DST_KEY="${DST_PATH#/}"

  SRC_EXISTS=0
  DST_EXISTS=0
  grep -Fxq "$SRC_KEY" "$INVENTORY" && SRC_EXISTS=1
  grep -Fxq "$DST_KEY" "$INVENTORY" && DST_EXISTS=1

  if [[ $SRC_EXISTS -eq 1 ]]; then
    TO_MOVE+=("$SRC_KEY|$DST_KEY")
  elif [[ $DST_EXISTS -eq 1 ]]; then
    SKIP_ALREADY_DONE=$((SKIP_ALREADY_DONE + 1))
  else
    SKIP_MISSING_BOTH=$((SKIP_MISSING_BOTH + 1))
    echo "  WARN: neither source nor destination exists for: $SRC_KEY → $DST_KEY" >&2
  fi
done < <(echo "$PLAN_JSON" | jq -r "$JQ_FILTER")

PLANNED="${#TO_MOVE[@]}"
echo "Plan:"
echo "  Moves planned:           ${PLANNED}"
echo "  Skipped (already done):  ${SKIP_ALREADY_DONE}"
echo "  Skipped (neither side):  ${SKIP_MISSING_BOTH}"
echo

if [[ $PLANNED -eq 0 ]]; then
  echo "Nothing to do."
  exit 0
fi

if [[ $EXECUTE -eq 1 ]]; then
  echo "*** REMINDER: have you run scripts/backup-media-bucket.sh ${BUCKET} ?"
  echo "*** aws s3 mv is destructive; bucket versioning + local sync are your safety net."
  echo
fi

# --- execute / dry-run ---
do_move() {
  local src="$1" dst="$2"
  if [[ $EXECUTE -eq 1 ]]; then
    aws s3 mv "s3://${BUCKET}/${src}" "s3://${BUCKET}/${dst}" --only-show-errors
  else
    echo "  aws s3 mv s3://${BUCKET}/${src} s3://${BUCKET}/${dst}"
  fi
}
export -f do_move
export BUCKET EXECUTE

FAILED=0
if [[ $EXECUTE -eq 1 ]]; then
  echo "Executing moves with concurrency ${CONCURRENCY}..."
  # Use xargs for parallelism. Each line: "src|dst".
  TMP_PLAN="$(mktemp)"
  for entry in "${TO_MOVE[@]}"; do echo "$entry"; done > "$TMP_PLAN"

  if ! cat "$TMP_PLAN" | xargs -P "$CONCURRENCY" -I{} bash -c '
    entry="{}"
    src="${entry%%|*}"
    dst="${entry##*|}"
    do_move "$src" "$dst"
  '; then
    FAILED=1
  fi
  rm -f "$TMP_PLAN"
else
  for entry in "${TO_MOVE[@]}"; do
    src="${entry%%|*}"
    dst="${entry##*|}"
    do_move "$src" "$dst"
  done
fi

# --- verification ---
echo
echo "Verifying..."
aws s3 ls "s3://${BUCKET}/" --recursive | awk '{print $4}' | sort > "$INVENTORY"

LEGACY_RESIDUE=0
while IFS=$'\t' read -r SRC_PATH DST_PATH; do
  SRC_KEY="${SRC_PATH#/}"
  if grep -Fxq "$SRC_KEY" "$INVENTORY"; then
    if [[ $EXECUTE -eq 1 ]]; then
      LEGACY_RESIDUE=$((LEGACY_RESIDUE + 1))
      echo "  RESIDUE: legacy object still present after move: $SRC_KEY" >&2
    fi
  fi
done < <(echo "$PLAN_JSON" | jq -r "$JQ_FILTER")

echo
echo "Summary:"
echo "  Mode:                    ${MODE}"
echo "  Moves planned/attempted: ${PLANNED}"
echo "  Skipped (already done):  ${SKIP_ALREADY_DONE}"
echo "  Skipped (neither side):  ${SKIP_MISSING_BOTH}"
echo "  Residue after execute:   ${LEGACY_RESIDUE}"

if [[ $FAILED -eq 1 || $LEGACY_RESIDUE -gt 0 ]]; then
  exit 2
fi

if [[ $EXECUTE -eq 0 ]]; then
  echo
  echo "This was a DRY RUN. Re-run with --execute to perform the moves."
fi
