name: compile_blazor

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      working-directory: ./web
      with:
        dotnet-version: 5.0.300
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build